name: lint-js

on: push

defaults:
  run:
    working-directory: ./app

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: node_modules-${{ env.cache-name }}
          restore-keys: node_modules-
      - run: npm i
      - run: npm run lint
